### ISSUE TITLE
سلام

### ISSUE THREAD

**Issue by webchii** [Sina-Soltani/Parbad.Samples#10]
سلام وقت بخیر
من از نمونه asp.net webfroms استفاده کردم که در تصویر زیر هم نمونه کد را زدم اما get weay بصورت درست دریافت نمیشود میشه لطفا راهنمایی کنید مشکل چیست ؟

        protected void BtnPay_Click(object sender, EventArgs e)
        {
            // استفاده به صورت استاتیک و بدون تزریق وابستگی

            var result = StaticOnlinePayment.Instance.Request(Gateways.["555syennstgnwk"], 123, 25000, "http://www.mywebsite.com/foo/bar/");

            if (result.IsSucceed)
            {
                // کاربر را به سمت درگاه بانکی هدایت میکند
                // همچنین بهتر است کد رهگیری که در شئ نتیجه است را، برای فاکتور مورد نظر در پایگاه داده خودتان ذخیره کنید
                result.GatewayTransporter.Transport();
            }
            else
            {
                // درخواست پرداخت موفقیت آمیز نبود
            }
        }

**Comment by Sina-Soltani** [comment]
درود
متوجه منظور شما نمیشم. منظورتون چی هست از به صورت درست دریافت نمی شود؟

آموزش ها و نمونه کدها کاملا شفاف همه چیز رو توضیح دادن. لطفا اونها رو بررسی کنید و ازشون استفاده کنید

نمونه کد برای WebForms

https://github.com/Sina-Soltani/Parbad.Samples/blob/master/Web/Parbad.Sample.WebForm/PayRequest.aspx.cs

**Comment by webchii** [comment]
سلام
ببینید من قصد اتصال به درگاه ایدی پی را دارم طبق آموزشها هم پیش رفتم و  کد زیر رانوشتم 

    public partial class Register_Course : System.Web.UI.Page
    {
        EpsilonContext Context = new EpsilonContext();
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
                ListCourse();
        }

        protected void getIP()
        {
            string IPaddr = string.Empty;
            if (HttpContext.Current.Request.ServerVariables["HTTP_X_FORWARDER_FOR"] != null)
            {
                IPaddr = HttpContext.Current.Request.ServerVariables["HTTP_X_FORWARDER_FOR"].ToString();
            }
            else if (HttpContext.Current.Request.UserHostAddress.Length != 0)
            {
                IPaddr = HttpContext.Current.Request.UserHostAddress;
            }
            lblinfo.Visible = false;
            lblinfo.InnerText = IPaddr;
        } //گرفتن ای پی کار

        public string getPersianNumber(string data)
        {
            for (int i = 48; i < 58; i++)
            {
                data = data.Replace(Convert.ToChar(i), Convert.ToChar(1728 + i));
            }
            return data;
        }

        protected void ListCourse()
        {
            ddlcourse.DataSource = (from c in Context.Courses
                                    select new
                                    {
                                        c.Id,
                                        c.Name
                                    }).ToList();
            ddlcourse.DataTextField = "Name";
            ddlcourse.DataValueField = "Id";
            ddlcourse.DataBind();
        }

        protected void icoUpdate_Click(object sender, ImageClickEventArgs e)
        {
            int ci = Convert.ToInt32(ddlcourse.SelectedValue);
            var course = Context.Courses.Find(ci);
            var teach = Context.Teachers.Find(course.TeacherId);
            var person = Context.Persons.Find(teach.PepoleId);
            int ds = Convert.ToInt32(course.Starttime.ToString("MM"));
            int dn = Convert.ToInt32(DateTime.Now.ToString("MM"));
            int de = Convert.ToInt32(course.Endtime.ToString("MM"));
            int dt;
            if (dn > ds)
                dt = dn - ds;
            else
                dt = de - dn;

            int t = (dt * 4) * course.Price;

            lbl1.InnerText = string.Format("نام دوره ی آموزشی : {0}",course.Name);
            lbl2.InnerText = string.Format("نام استاد : {0} {1}", person.Firstname, person.Lastname);
            lbl3.InnerText = getPersianNumber(string.Format("تعداد جلسات : {0} جلسه",(dt*4).ToString()));
            lbl4.InnerText = getPersianNumber(string.Format("مبلغ دوره : {0} تومان",t.ToString("0,0")));
            d2.Visible = true;
            d3.Visible = true;
        }

        protected void iconback_Click(object sender, ImageClickEventArgs e)
        {
            Response.Redirect("Testing_and_scheduling.aspx", true);
        }

        protected void rb1_CheckedChanged(object sender, EventArgs e)
        {
            int ci = Convert.ToInt32(ddlcourse.SelectedValue);
            var course = Context.Courses.Find(ci);
            var teach = Context.Teachers.Find(course.TeacherId);
            var person = Context.Persons.Find(teach.PepoleId);
            int ds = Convert.ToInt32(course.Starttime.ToString("MM"));
            int dn = Convert.ToInt32(DateTime.Now.ToString("MM"));
            int de = Convert.ToInt32(course.Endtime.ToString("MM"));
            int dt;
            if (dn > ds)
                dt = dn - ds;
            else
                dt = de - dn;

            int t = (dt * 4) * course.Price;

            if (rb1.Checked == true)
            {
                txtprice.Visible = true;
                txtprice.Value = getPersianNumber(t.ToString());
            }
            else
            {
                txtprice.Visible = false;
            }
        }

        protected void BtnPay_Click(object sender, EventArgs e)
        {
            // استفاده به صورت استاتیک و بدون تزریق وابستگی
        }

        private void Gateways(IInvoiceBuilder obj)
        {
            throw new NotImplementedException();
        }

        protected void btnRegister_Click(object sender, EventArgs e)
        {
            IPaymentRequestResult result = StaticOnlinePayment.Instance.Request("981b-s669s-fe-4f54-907d-18028ceca42c", 123, 30000, "http://epssof.ir");
            if (result.IsSucceed)
            {
                // کاربر را به سمت درگاه بانکی هدایت میکند
                // همچنین بهتر است کد رهگیری که در شئ نتیجه است را، برای فاکتور مورد نظر در پایگاه داده خودتان ذخیره کنید
                result.GatewayTransporter.Transport();
            }
            else
            {
                // درخواست پرداخت موفقیت آمیز نبود
            }
        }

        public void ConfigureServices(IServiceCollection services)
        {   
            services.AddParbad()
                .ConfigureGateways(gateways =>
                {
                    gateways
                        .AddIdPay()
                        .WithOptions(options =>
                        {
                            options.ApiRequestUrl = "981b6336-89fe-4f54-907d-18028ceca42c";
                            options.ApiVerificationUrl = "http://epssoft.ir";
                        });
                });
        }

        public void Configuration(IAppBuilder app)
        {
            var parbad = ParbadBuilder.CreateDefaultBuilder()
                .ConfigureGateways(gateways =>
                {
                    gateways
                       .AddIdPay()
                       .WithOptions(options => options.ApiRequestUrl = "981b-s669s-fe-4f54-907d-18028ceca42c");
                })
                .Build();

            app.Use(parbad.Services);
        }


    }

درگاه ایدی پی کد API-Key میدهد اما در نمونه ها این مورد نبود میشه لطفا راهنمایی بفرمایید 
ممنون میشم

**Comment by Sina-Soltani** [comment]
۱. وب سایت شما باید با Owin سازگاری داشته باشه. اگر در پروژه شما Owin وجود نداره پس اصلا از این ابزار نمیتونید استفاده کنید

۲. در کلاس Startup که برای تنظیمات Owin و وب سایت هست،‌ باید کدهای تنظیم درگاه اضافه بشه. ظاهرا شما اصلا این کار رو نکردید چون متد تنظیمات رو داخل یک صفحه وب به اسم ثبت نام دوره اضافه کردید که اصلا هیچ ارتباطی با تنظیمات درگاه ها نداره. لطفا آموزش ها رو نگاه کنید. همه چیز شفاف توضیح داده شده و جای هیچ سوالی باقی نمیزاره.

۳. دوباره تکرار میکنم،‌ لطفا مثال‌ها رو نگاه کنید همه چیز شفافه. برای نمونه کاملا واضح ذکر شده که پارامتر اول در متد Request نام درگاه هست. در صورتیکه شما یک GUID دارید به متد میدید.

[آموزش تنظیمات](https://github.com/Sina-Soltani/Parbad/wiki/Configuration)
[آموزش استفاده از متد‌های پرداخت و تایید پرداخت](https://github.com/Sina-Soltani/Parbad/wiki/Payment)

**Comment by webchii** [comment]
بله درسته من باید یک کلاس تعریف میکردم
using Owin;
using Parbad;
using Parbad.Builder;
using Parbad.Gateway.IdPay;
using Parbad.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Domain.Entity
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            var onlinePaymentAccessor = ParbadBuilder.CreateDefaultBuilder()
                .ConfigureGateways(gateways=>
                {
                    gateways.AddIdPay()
                    .WithOptions(option => option.ApiRequestUrl = "981b6336-89fe-4f54-907d-18028ceca42c");
                })
                .Build();
        }

        private void ConfigureHttpContext(Func<object, IHttpContextBuilder> p)
        {
            throw new NotImplementedException();
        }
    }
}
فقط الان سوالی که از شما داشتم اینه که  برای getway از کجا مشخص میشه اینو متوجه نشدم و اینکه کدتون که دانلود کردم از یک dropdownlist داره میخونه من نفهمیدم من که از api استفاده میکنم چگونه باید بکار ببرم

**Comment by Sina-Soltani** [comment]
نمونه کد تنظیمات رو از کلاس زیر کپی کنید و در پروژه خودتون Paste کنید

https://github.com/Sina-Soltani/Parbad.Samples/blob/master/Web/Parbad.Sample.WebForm/App_Start/ParbadConfig.cs

در قسمت تنظیمات درگاه، درگاه IdPay رو به صورت زیر اضافه و تنظیم کنید

```c#
public static IOnlinePaymentAccessor Configure()
{
    return ParbadBuilder.CreateDefaultBuilder()
        .ConfigureGateways(gateways =>
        {
            gateways
                .AddIdPay()
                .WithAccounts(accounts =>
                {
                    accounts.AddInMemory(account =>
                    {
                        account.Api = "981b6336-89fe-4f54-907d-18028ceca42c";
                    });
                });
        })
        .ConfigureHttpContext(builder => builder.UseOwinFromCurrentHttpContext())
        .ConfigureStorage(builder => builder.UseEfCore()) // آموزش تنظیم پایگاه داده رو مشاهده کنید
        .Build();
}
```

کدهای پرداخت رو از کلاس زیر کپی کنید و در پروژه خودتون Paste کنید

https://github.com/Sina-Soltani/Parbad.Samples/blob/master/Web/Parbad.Sample.WebForm/PayRequest.aspx.cs

قسمت پرداخت رو به شکل زیر برای خودتون تغییر بدید

```c#
var verifyUrl = $"{Request.Url.Scheme}://{Request.Url.Authority}/Verify"; // آدرس بازگشت از درگاه به وب سایت خودتون رو تنظیم کنید

            var result = StaticOnlinePayment.Instance.Request(invoice =>
            {
                invoice
                    .SetTrackingNumber(...) // شماره پیگیری رو تنظیم کنید
                    .SetAmount(1000) // مقدار هزینه
                    .SetCallbackUrl(verifyUrl) // تنظیم آدرس بازگشتی
                    .UseIdPay();
            });

            // Save the result.TrackingNumber in your database.

            if (result.IsSucceed)
            {
                result.GatewayTransporter.Transport();
            }
            else
            {
                      // عملیات ناموفق بود
            }
```

لطفا در صورت عدم آشنایی با کدنویسی و وب،‌ از اطرافیان کمک بگیرید، چون بنده فرصتی برای آموزش کدنویسی نمیتونم بزارم و اینگونه مسائل در واقع هیچگونه ارتباطی با این ابزار ندارند

**Comment by webchii** [comment]
ممنون از پاسخگوییتون
نیازی به آموزش نبود کمی نمونه هایی که قرار داده شده بود نیاز به راهنمایی بیشتر داشتم با این حال ممنون
