### ISSUE TITLE
DotNet6 + Sql Storage

### ISSUE THREAD

**Issue by feryt20** [Sina-Soltani/Parbad.Samples#11]
سلام و درود
در دات نت کور 6 فایل استارتاپ نداریم
ممکنه راهنمایی کنید چجوری ذخیره سازی در دیتابیس رو پیاده کنیم؟

`const string connectionString = "Connection String";
                    var migrationsAssemblyName = typeof(Startup).Assembly.GetName().Name; // An Assembly where your migrations files are in it. In this sample the files are in the same project.

                    options.ConfigureDbContext = db => db.UseSqlServer(connectionString, sql =>
                    {
                        sql.MigrationsAssembly(migrationsAssemblyName);
                        sql.MigrationsHistoryTable("TABLE NAME");
                    });`

**Comment by Sina-Soltani** [comment]
درود

 var migrationsAssemblyName = typeof(Program).Assembly.GetName().Name;
