### ISSUE TITLE
شخصی سازی

### ISSUE THREAD

**Issue by mmo1383** [Sina-Soltani/Parbad.Samples#9]
چه طور یک ستون اضافی در جدول 
payments
ایجاد کنم 
مثل orderid

**Comment by Sina-Soltani** [comment]
امکان پذیر نیست
جدول‌های پَرباد، برای مصرف داخلی خود پَرباد هست

هر کاری که قصد انجامش رو دارید، روی جداول دیگه خودتون انجام بدید
هر اطلاعاتی لازم دارید، میتونید موقع دریافت پاسخ از متدهای پرداخت، بدست بیارید
